update guide to use ucp hosted login service
Universal-Connect-Project/universal-connect-widget pull request #20
Opened 2024-01-04 13:55 UTC by sophtron-jishun

The required components  `ucp-login` `ucp-analytics` and `unifield-search`  are now hosted in UCP account and sophtron hard dependency is now removed from universal vcs. 

This readme change points credentials process to the new-but-temporary hosted ucp-login page, currently using sophtron-prod.com dns while waiting for access to UCP dns. 

The last merged PR reverted the default config method and added [DotEnv](https://www.npmjs.com/package/dotenv)  as this is the more common way how js handles local config, also is deployment-friendly

2024-01-04 22:59 UTC, tphalp commented
I think we should add the `.env` files to .gitignore, so we don't accidentally check-in the file with sensitive information. See this comment from the Dotenv repo: https://github.com/motdotla/dotenv/issues/74#issuecomment-273929197

2024-01-04 23:06 UTC, sophtron-jishun commented
it is in `.gitignore` : 
https://github.com/Universal-Connect-Project/universal-connect-widget/blob/b8182b18dff33b9c89a31de70ad78fc4f6de7d6e/.gitignore#L4

2024-01-04 23:07 UTC, tphalp commented
> it is in `.gitignore` :
> 
> https://github.com/Universal-Connect-Project/universal-connect-widget/blob/b8182b18dff33b9c89a31de70ad78fc4f6de7d6e/.gitignore#L4

Ah, my bad...I looked, but missed it. Thank you!

2024-01-04 23:15 UTC, tphalp approved these changes, later dismissed
Thank you for this, Jishun.

2024-01-04 23:49 UTC, Craiting commented on application/README.md
> +USE `.evn` FILE
```suggestion
USE `.env` FILE
```

2024-01-05 16:45 UTC, Craiting reviewed
Just a couple typos I noticed

2024-01-05 16:45 UTC, Craiting commented on application/README.md
> +## FIRST: Get familia with [dotenv](https://www.npmjs.com/package/dotenv)
```suggestion
## FIRST: Get familiar with [dotenv](https://www.npmjs.com/package/dotenv)
```

2024-01-05 16:45 UTC, Craiting commented on application/README.md
> +  USE `.evn` FILE
```suggestion
  USE `.env` FILE
```

2024-01-05 19:42 UTC, tphalp requested changes

2024-01-05 19:42 UTC, tphalp commented on application/README.md
> +  DO NOT put any credentials in any of the js files. this way it will get accidentially committed and leaked to public
```suggestion
  DO NOT put any credentials in any of the js files. If you do so, it could accidentally get committed and leaked to public.
```

2024-01-05 19:42 UTC, tphalp commented on application/README.md
> +DO NOT put any credentials in any of the js files. this way it will get accidentially committed and leaked to public
```suggestion
DO NOT put any credentials in any of the js files. If you do so, it could accidentally get committed and leaked to public.
```

2024-01-05 19:47 UTC, tphalp approved these changes

2024-01-05 19:59 UTC, merged