auth provider selecting on request
Universal-Connect-Project/universal-connect-widget pull request #57
Opened 2024-04-09 13:26 UTC by sophtron-jishun

- Allow selecting auth provider by config 
- Add local auth provider, 
- Handle provider param in authcode and allow dynamic selecting auth provider by request

2024-04-09 19:43 UTC, Craiting requested changes
Nice, I like the local auth option. Looks good other than the typo I pointed out.

2024-04-09 19:43 UTC, Craiting commented on application/server/config.js
> +  LocalAuthPhraze: 'I am authentic', // a static auth phraze to be encrypted by the key above at caller side.
typo
```suggestion
  LocalAuthPhrase: 'I am authentic', // a static auth phrase to be encrypted by the key above at caller side. 
```

2024-04-09 19:43 UTC, Craiting commented on application/server/serviceClients/authClient/local.js
> +    if(token === config.LocalAuthPhraze){
```suggestion
    if(token === config.LocalAuthPhrase){ 
```

2024-04-09 22:29 UTC, sophtron submitted a review, later dismissed

2024-04-10 15:36 UTC, Craiting approved these changes

2024-04-10 15:37 UTC, merged